### ISSUE TITLE
Covariates and Predictions

### ISSUE THREAD

**Issue by CamFreshwater** [pbs-assess/juvenile-salmon-index#2]
I've started trying to fit sdmTMB models with relevant covariates (Julian day and depth) and while the models converge, generating predictions has proven troublesome. So far I've identified two, potentially related issues, both of which are probably linked to my unfamiliarity with this sort of spatial data!

First, I'm not sure how to design a reasonably-sized prediction grid for Julian day since, unlike the depth covariate data in the example qcs_grid, it seems necessary to assign the full range of sampling days _and_ sampling years to any spatial location. This seems to create a matrix that is too large for at least my local computer to handle. I'm not sure if it's worth trying to address this problem since perhaps it is more appropriate to treat sub-annual time as an ordinal rather than continuous variable in which case we can just roll it up to a weekly or monthly scale to create predictions sufficient for our purposes. Thoughts? Note that I haven't tried implementing this yet because I'm not sure if sdmTMB can handle these ordinal covariates.

Second, I've also run into issues fitting a model with just depth data. Predictions are generated, but when I try to plot them a "too many elements specified" error is thrown. I'm not sure what's going on here because the depth data are attributed to a single spatial location resulting in a prediction grid that is similar in size to the qcs_grid example. Any ideas?

If you'd like to play around with it yourself the most recently pushed version of smdTMBPrac.R should include all the necessary data.

**Comment by seananderson** [comment]
I think you want to predict for a single point in time, don't you? Probably the mean date of the survey or some other convenient or meaningful value. Things that actually vary spatially, like depth, are things that you want to predict at specific values. Everything else you are standardizing to a fixed value.

For the second problem, what function is generating that error? Can you do a `traceback()`? Is this error coming from ggplot?

**Comment by CamFreshwater** [comment]
Having thought about it, I suppose you're right on the first point. Ideally we would like to incorporate data from multiple surveys, which have occurred (very approximately) during 3 different periods and will help us account for the seasonal changes in distribution that drive a big portion of the variability in salmon abundance. However I think that might be a bit much for now so I'll begin with only one survey and drop Julian day as a predictor for now.

The second problem does seem to originate with ggplot and faceting (pasted below), but I think it's driven by the prediction grid I created. I don't have a spatial data file on hand to develop a prediction grid with the relevant depth distribution. I tried something hacky, but I'm pretty sure it has too many gaps. 

Do you have one on hand for the west coast that I could process for our needs or have a recommended source? Also what's best practice for addressing areas that are within the survey domain based on the bounding box, but that are known to have zero catch (e.g. land)? Presumably including covariates, such as depth, that predict catch is one approach or should they just be excluded entirely so that we plot, for example, Queen Charlotte Sound separately from WCVI?

```17: matrix(NA_character_, nrow = nrow, ncol = ncol)
16: f(...)
15: (function (...) 
    f(...))(data, panel_params, coord, hjust = 0.5, vjust = 0.5, 
        interpolate = FALSE)
14: do.call(self$draw_panel, args)
13: FUN(X[[i]], ...)
12: lapply(split(data, data$PANEL), function(data) {
        if (empty(data)) 
            return(zeroGrob())
        panel_params <- layout$panel_params[[data$PANEL[1]]]
        do.call(self$draw_panel, args)
    })
11: f(..., self = self)
10: self$geom$draw_layer(data, self$geom_params, layout, layout$coord)
9: f(..., self = self)
8: l$draw_geom(d, layout)
7: (function (l, d) 
   l$draw_geom(d, layout))(dots[[1L]][[1L]], dots[[2L]][[1L]])
6: mapply(FUN = f, ..., SIMPLIFY = FALSE)
5: Map(function(l, d) l$draw_geom(d, layout), plot$layers, data)
4: ggplot_gtable.ggplot_built(data)
3: ggplot_gtable(data)
2: print.ggplot(x)
1: (function (x, ...)```

**Comment by seananderson** [comment]
Quick answer to the first point: totally reasonable to keep day of year in the model (possibly as a polynomial) but then predict at a single day of year.

**Comment by seananderson** [comment]
To start with, forget about depth. The spatial field will account for most of it. Otherwise, yes I can point you to data sources later.

**Comment by CamFreshwater** [comment]
Yup prediction grid works fine with a single daily prediction and depth removed. Issue number 2 was due to the prediction dataframe having a bunch of gaps (basically where we never fished because it's land). Still not sure what best practice is for these locations since intuitively we don't want/need to make predictions where we know abundance is 0, but we can discuss that later on.
